/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as AppointmentsSlugRouteImport } from './routes/appointments/$slug'
import { Route as CraftIndexRouteImport } from './routes/craft/index'
import { Route as CraftSlugRouteImport } from './routes/craft/$slug'
import { Route as FieldNotesIndexRouteImport } from './routes/field-notes/index'
import { Route as FieldNotesSlugRouteImport } from './routes/field-notes/$slug'
import { Route as FramesIndexRouteImport } from './routes/frames/index'
import { Route as FramesFilterRouteImport } from './routes/frames/$filter'
import { Route as HouseIndexRouteImport } from './routes/house/index'
import { Route as HouseSlugRouteImport } from './routes/house/$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/appointments/',
  path: '/appointments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsSlugRoute = AppointmentsSlugRouteImport.update({
  id: '/appointments/$slug',
  path: '/appointments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftIndexRoute = CraftIndexRouteImport.update({
  id: '/craft/',
  path: '/craft/',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftSlugRoute = CraftSlugRouteImport.update({
  id: '/craft/$slug',
  path: '/craft/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesIndexRoute = FieldNotesIndexRouteImport.update({
  id: '/field-notes/',
  path: '/field-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldNotesSlugRoute = FieldNotesSlugRouteImport.update({
  id: '/field-notes/$slug',
  path: '/field-notes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesIndexRoute = FramesIndexRouteImport.update({
  id: '/frames/',
  path: '/frames/',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesFilterRoute = FramesFilterRouteImport.update({
  id: '/frames/$filter',
  path: '/frames/$filter',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseIndexRoute = HouseIndexRouteImport.update({
  id: '/house/',
  path: '/house/',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseSlugRoute = HouseSlugRouteImport.update({
  id: '/house/$slug',
  path: '/house/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/appointments/$slug': typeof AppointmentsSlugRoute
  '/craft/$slug': typeof CraftSlugRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/frames/$filter': typeof FramesFilterRoute
  '/house/$slug': typeof HouseSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/craft/': typeof CraftIndexRoute
  '/field-notes/': typeof FieldNotesIndexRoute
  '/frames/': typeof FramesIndexRoute
  '/house/': typeof HouseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/appointments/$slug': typeof AppointmentsSlugRoute
  '/craft/$slug': typeof CraftSlugRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/frames/$filter': typeof FramesFilterRoute
  '/house/$slug': typeof HouseSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/craft': typeof CraftIndexRoute
  '/field-notes': typeof FieldNotesIndexRoute
  '/frames': typeof FramesIndexRoute
  '/house': typeof HouseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/cookies': typeof CookiesRoute
  '/privacy': typeof PrivacyRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/warranty': typeof WarrantyRoute
  '/appointments/$slug': typeof AppointmentsSlugRoute
  '/craft/$slug': typeof CraftSlugRoute
  '/field-notes/$slug': typeof FieldNotesSlugRoute
  '/frames/$filter': typeof FramesFilterRoute
  '/house/$slug': typeof HouseSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/craft/': typeof CraftIndexRoute
  '/field-notes/': typeof FieldNotesIndexRoute
  '/frames/': typeof FramesIndexRoute
  '/house/': typeof HouseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/cookies'
    | '/privacy'
    | '/shipping'
    | '/terms'
    | '/warranty'
    | '/appointments/$slug'
    | '/craft/$slug'
    | '/field-notes/$slug'
    | '/frames/$filter'
    | '/house/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/appointments/'
    | '/craft/'
    | '/field-notes/'
    | '/frames/'
    | '/house/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/cookies'
    | '/privacy'
    | '/shipping'
    | '/terms'
    | '/warranty'
    | '/appointments/$slug'
    | '/craft/$slug'
    | '/field-notes/$slug'
    | '/frames/$filter'
    | '/house/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/appointments'
    | '/craft'
    | '/field-notes'
    | '/frames'
    | '/house'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/cookies'
    | '/privacy'
    | '/shipping'
    | '/terms'
    | '/warranty'
    | '/appointments/$slug'
    | '/craft/$slug'
    | '/field-notes/$slug'
    | '/frames/$filter'
    | '/house/$slug'
    | '/legal/$slug'
    | '/product/$slug'
    | '/appointments/'
    | '/craft/'
    | '/field-notes/'
    | '/frames/'
    | '/house/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  CookiesRoute: typeof CookiesRoute
  PrivacyRoute: typeof PrivacyRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  WarrantyRoute: typeof WarrantyRoute
  AppointmentsSlugRoute: typeof AppointmentsSlugRoute
  CraftSlugRoute: typeof CraftSlugRoute
  FieldNotesSlugRoute: typeof FieldNotesSlugRoute
  FramesFilterRoute: typeof FramesFilterRoute
  HouseSlugRoute: typeof HouseSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  ProductSlugRoute: typeof ProductSlugRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
  CraftIndexRoute: typeof CraftIndexRoute
  FieldNotesIndexRoute: typeof FieldNotesIndexRoute
  FramesIndexRoute: typeof FramesIndexRoute
  HouseIndexRoute: typeof HouseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/appointments'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments/$slug': {
      id: '/appointments/$slug'
      path: '/appointments/$slug'
      fullPath: '/appointments/$slug'
      preLoaderRoute: typeof AppointmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/': {
      id: '/craft/'
      path: '/craft'
      fullPath: '/craft/'
      preLoaderRoute: typeof CraftIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft/$slug': {
      id: '/craft/$slug'
      path: '/craft/$slug'
      fullPath: '/craft/$slug'
      preLoaderRoute: typeof CraftSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes/': {
      id: '/field-notes/'
      path: '/field-notes'
      fullPath: '/field-notes/'
      preLoaderRoute: typeof FieldNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-notes/$slug': {
      id: '/field-notes/$slug'
      path: '/field-notes/$slug'
      fullPath: '/field-notes/$slug'
      preLoaderRoute: typeof FieldNotesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/': {
      id: '/frames/'
      path: '/frames'
      fullPath: '/frames/'
      preLoaderRoute: typeof FramesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames/$filter': {
      id: '/frames/$filter'
      path: '/frames/$filter'
      fullPath: '/frames/$filter'
      preLoaderRoute: typeof FramesFilterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house/': {
      id: '/house/'
      path: '/house'
      fullPath: '/house/'
      preLoaderRoute: typeof HouseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/house/$slug': {
      id: '/house/$slug'
      path: '/house/$slug'
      fullPath: '/house/$slug'
      preLoaderRoute: typeof HouseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  CookiesRoute: CookiesRoute,
  PrivacyRoute: PrivacyRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  WarrantyRoute: WarrantyRoute,
  AppointmentsSlugRoute: AppointmentsSlugRoute,
  CraftSlugRoute: CraftSlugRoute,
  FieldNotesSlugRoute: FieldNotesSlugRoute,
  FramesFilterRoute: FramesFilterRoute,
  HouseSlugRoute: HouseSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  ProductSlugRoute: ProductSlugRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
  CraftIndexRoute: CraftIndexRoute,
  FieldNotesIndexRoute: FieldNotesIndexRoute,
  FramesIndexRoute: FramesIndexRoute,
  HouseIndexRoute: HouseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
